name: Uptime Monitor

on:
  schedule:
    - cron: "0 5 * * *"   # 1 AM EST (5:00 UTC)
    - cron: "0 16 * * *"  # 12 PM EST (16:00 UTC)
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run uptime logger
        run: |
          npm install
          node uptimeLogger.js

      - name: Commit & Push Results
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add uptime-log.json
          git commit -m "Twice daily update"
          git push